### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down这个错误怎么解

### ISSUE THREAD

**Issue by nssiwi** [YeYoot/xuexi.cn#2]
安装的aconda，python版本3.6，环境变量配置没错

**Comment by nssiwi** [comment]
在 `self.driver.quit()` 这里出错的

**Comment by nssiwi** [comment]
> 是任务全部完成后出的错吧？要是嫌报错不好看可以把这行代码注释掉...不影响脚本使用，我看看该怎么解决先。。。

我查了很久，貌似selenium的这个错误很常见，试了很多还是没能解决

**Comment by YeYoot** [comment]
这个问题已经解决了，和python的版本有点关系，3.5的就没问题，3.7就会报错，但是现在已经解决了
